//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzerginKurs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class foreignschool_kpEntities : DbContext
    {
        public foreignschool_kpEntities()
            : base("name=foreignschool_kpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RoleNikit> RoleNikit { get; set; }
        public virtual DbSet<ServiceNikita> ServiceNikita { get; set; }
        public virtual DbSet<UserNikit> UserNikit { get; set; }
        public virtual DbSet<UserServiceNikit> UserServiceNikit { get; set; }
    }
}
