//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzerginKurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceNikita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceNikita()
        {
            this.UserServiceNikit = new HashSet<UserServiceNikit>();
        }
    
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Id { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserServiceNikit> UserServiceNikit { get; set; }
    }
}
