//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzerginKurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserServiceNikit
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ServiceId { get; set; }
    
        public virtual ServiceNikita ServiceNikita { get; set; }
        public virtual UserNikit UserNikit { get; set; }
    }
}
