//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzerginKurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNikit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserNikit()
        {
            this.UserServiceNikit = new HashSet<UserServiceNikit>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Photo { get; set; }
        public string Education { get; set; }
    
        public virtual RoleNikit RoleNikit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserServiceNikit> UserServiceNikit { get; set; }
    }
}
